/* This file is automatically generated with cr2res_gen_eop_table.py */
#ifndef CRIRES_IO_EOP_TABLE_H
#define CRIRES_IO_EOP_TABLE_H

#define     EOP_TABLE_SIZE     5
static double eop_table_double_entries[EOP_TABLE_SIZE][4]={
    { 954.2587, 2.2, 1, 1},
    { 954.2587, 2.3, 1, 1},
    { 954.2587, 2.4, 1, 1},
    { 954.2587, 2.5, 1, 1},
    { 954.2587, 2.6, 1, 1}
} ;

static const char * eop_table_string_entries[EOP_TABLE_SIZE]={
    "I",
    "I",
    "I",
    "C",
    "I"
} ;

#endif

