#!/bin/sh

cp Iiinstrument.xml Iiinstrument.xml.for_cvs
sed -i "s%/diskb/$USER/reflex_data%UVES_DATA_PATH_TO_REPLACE%g" Iiinstrument.xml.for_cvs
sed -i "s%/home/$USER//local/\(.*uves\)-[0-9]\.[0-9]\.[0-9][0-9]%@prefix@/\1-@VERSION@%g" Iiinstrument.xml.for_cvs
sed -i "s%Iiinstrument Workflow (v\. [0-9]\.[0-9]\.[0-9])%Iiinstrument Workflow (v\. @VERSION@)%g" Iiinstrument.xml.for_cvs
#A graphical diff view like kdiff3 can be used instead of a plain diff
diff Iiinstrument.xml.for_cvs Iiinstrument.xml.in > cvs_diff
#Print message
echo "Check the file cvs_diff to see the differences with respect to CVS"
echo "If you are satisfied, execute the following commands:"
echo "cp -f Iiinstrument.xml.for_cvs Iiinstrument.xml.in"
echo "cvs ci Iiinstrument.xml.in"
